version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mongo-starter-fiber:latest  # Set the image name
    container_name: mongo-starter-fiber  # Set the container name
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo-starter-fiber-db  # Set the container name for MongoDB
    ports:
      - "27017:27017"
    env_file: .env  # Reference the .env file here for MongoDB credentials
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
